name: ci

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install poetry
      - run: poetry config virtualenvs.create false
      - run: poetry install
      - run: ruff check .
      - run: mypy boreas --ignore-missing-imports --follow-imports skip
      - run: xenon --max-average A --max-modules B --max-absolute B .
      - run: pytest --verbose --cov app --cov-report=xml --junitxml=report.xml tests

  build:
    if: github.event_name == 'push'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/login-action@v3
        with:
          registry: binkcore.azurecr.io
          username: binkcore
          password: ${{ secrets.ACR_BINKCORE_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            binkcore.azurecr.io/${{ github.event.repository.name }}:${{ github.ref_name }}
            binkcore.azurecr.io/${{ github.event.repository.name }}:latest

  release:
    if: github.event_name == 'push'
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - dev
          - staging
          - prod
    environment:
      name: ${{ matrix.environment }}
    container: ghcr.io/binkhq/tagbot:latest
    steps:
      - run: |
          tagbot \
            --username binkcore \
            --password ${{ secrets.ACR_BINKCORE_PASSWORD }} \
            --source binkcore.azurecr.io/${{ github.event.repository.name }}:${{ github.ref_name }} \
            --tag ${{ matrix.environment }}-${{ github.ref_name }}
          tagbot \
            --username binkcore \
            --password ${{ secrets.ACR_BINKCORE_PASSWORD }} \
            --source binkcore.azurecr.io/${{ github.event.repository.name }}:${{ github.ref_name }} \
            --tag ${{ matrix.environment }}
